# -*- coding: utf-8 -*-
{
    'name': "Solibre Useability",

    'summary': """Useability updates and features""",

    'description': """
        Features
            - stock localisation
    """,

    'author': "Solibre",
    'category': 'Uncategorized',
    'version': '0.1',

    'depends': ['base',
                'sms',
                'stock',
                'purchase_requisition',
                'sale_crm',
                'project',
                'account',
                'hr_timesheet',
                'website_sale',
                'fleet',
                'mrp',
                'website_sale_delivery',
                'accounting_pdf_reports',
                'hr_holidays',
                'delivery',
                'om_account_asset'],
    'installable':True,
    'data': [
        'views/product.xml',
        'views/picking.xml',
        'views/crm.xml',
        'views/iap.xml',
        'views/sms.xml',
        'views/partner.xml',
        'views/project.xml',
        'views/journal.xml',
        'views/payment.xml',
        'views/sale.xml',
        'views/account.xml',
        'views/stock_localisation.xml',
        'views/payment_request.xml',
        'views/requisition.xml',
        'views/purchase.xml',
        'views/leave_report.xml',
        'views/res_config.xml',
        'views/fleet.xml',
        'views/landing_cost.xml',  
        'views/product_barcode.xml',
        'views/users.xml',  
        'views/website.xml',   
        'views/subscription.xml',
        'views/timesheet.xml',
        'views/consignment.xml',
        'views/mrp.xml',
        'views/tax_report.xml',
        'templates/stock.xml',
        'templates/instagram.xml',
        'wizard/import_po_view.xml',
        'wizard/import_so_view.xml',
        'data/project.xml',
        'data/purchase.xml',
        'data/subscription.xml',
        'data/mail.xml',
        'data/sms.xml',
        'data/product.xml',
        'data/cron.xml',
        'security/ir.model.access.csv',
        'security/ir.rule.xml'
    ],
}