# -*- coding: utf-8 -*-
from . import stock_localisation
from . import product
from . import partner
from . import crm
from . import project
from . import analytic
from . import sale
from . import journal
from . import purchase
from . import requisition
from . import payment
from . import payment_request
from . import mail
from . import whatsapp_api
from . import sms
from . import leave_report
from . import users
from . import company
from . import account
from . import res_config
from . import payment
from . import fleet
from . import landing_cost
from . import website
from . import stock
from . import procurement
from . import mrp
from . import subscription
from . import consignment
from . import report
from . import instagram
from .import tax_report